### ISSUE TITLE
When project path name contains a space (" "), get URI is not absolute

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec-maven-plugin-1#7]
Found in releases 1.5.1-RC2 & RC3

I have this exception :
```
[ERROR] while resolving ../../common/meta/inject-ua-meta.xspec to /var/lib/jenkins/jobs/SIE-Magneto BUILD master/workspace/main/src/test/xspec/tfr/meta/inject-ua-meta.xspec
java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088)
	at org.xmlresolver.ResourceConnection.<init>(ResourceConnection.java:43)
	at org.xmlresolver.ResourceResolver.cacheStreamURI(ResourceResolver.java:123)
	at org.xmlresolver.ResourceResolver.resolveURI(ResourceResolver.java:238)
	at org.xmlresolver.Resolver.resolveResource(Resolver.java:82)
	at org.xmlresolver.Resolver.resolve(Resolver.java:93)
	at io.xspec.maven.xspecMavenPlugin.resolver.Resolver.resolve(Resolver.java:66)
	at io.xspec.maven.xspecMavenPlugin.utils.XSpecCounterCH.startElement(XSpecCounterCH.java:101)
```

**Comment by cmarchand** [comment]
Solved in 2.0.0-RC6
